In [4]:
import pandas as pd

def load_data(url):
    # read csv from github url
    # return pandas dataframe
    df = pd.read_csv(url)
    return df

# load inspections dataset
los_angeles_inspections_url = 'https://raw.githubusercontent.com/prathikr/CS_499_Final_Project/master/LOS_ANGELES_COUNTY_RESTAURANT_AND_MARKET_INSPECTIONS.csv'

df = load_data(los_angeles_inspections_url)
df.head()

,ACTIVITY DATE,OWNER ID,OWNER NAME,FACILITY ID,FACILITY NAME,RECORD ID,PROGRAM NAME,PROGRAM STATUS,PROGRAM ELEMENT (PE),PE DESCRIPTION,...,FACILITY CITY,FACILITY STATE,FACILITY ZIP,SERVICE CODE,SERVICE DESCRIPTION,SCORE,GRADE,SERIAL NUMBER,EMPLOYEE ID,Location
0,04/12/2017,OW0003351,AUDREY KIM BRIDAL COLLECTION,FA0010275,BOBA YA,PR0029878,BOBA YA,ACTIVE,1631,RESTAURANT (0-30) SEATS MODERATE RISK,...,LA MIRADA,CA,90638,1,ROUTINE INSPECTION,95,A,DAH2Z9080,EE0000744,NaN
1,04/12/2017,OW0181132,THAI CITY DUARTE INC.,FA0174471,THAI CITY RESTAURANT,PR0167479,THAI CITY RESTAURANT,ACTIVE,1635,RESTAURANT (31-60) SEATS HIGH RISK,...,DUARTE,CA,91010,1,ROUTINE INSPECTION,90,A,DACH7Y18F,EE0000120,NaN
2,04/13/2017,OW0125502,SWEE KOK CHER,FA0160544,SUSHI FIRE,PR0148634,SUSHI FIRE,ACTIVE,1635,RESTAURANT (31-60) SEATS HIGH RISK,...,DUARTE,CA,91010,1,ROUTINE INSPECTION,90,A,DAEOLNF0Z,EE0000120,NaN
3,04/13/2017,OW0010326,DOS MONTANAS LLC,FA0012454,TIPSY WINGS,PR0018288,TIPSY WINGS,INACTIVE,1638,RESTAURANT (61-150) SEATS HIGH RISK,...,EL MONTE,CA,91732,1,ROUTINE INSPECTION,95,A,DABTUPVHJ,EE0000188,POINT (-118.020082 34.07441)
4,04/19/2017,OW0107342,MARIELENA RODRIGUEZ,FA0144532,ARI'S SHOP,PR0130618,ARI'S SHOP,ACTIVE,1610,"FOOD MKT RETAIL (1-1,999 SF) LOW RISK",...,LOS ANGELES,CA,90012,1,ROUTINE INSPECTION,100,A,DAL4G6OJH,EE0001058,NaN

In [ ]:
# convert activity_date string to datetime object